[package]
name = "lc3-vm"
version = "0.1.0"
edition = "2021"

default-run = "main"

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "assembler"
path = "src/bin/assembler.rs"

[[bin]]
name = "disassembler"
path = "src/bin/disassembler.rs"
